apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-external-secret
  namespace: $NAMESPACE
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: inventory
        property: MYSQL_ROOT_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inventory-app-external-secret
  namespace: $NAMESPACE
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: inventory-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: inventory
        property: DB_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-external-secret
  namespace: $NAMESPACE
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-secrets
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: inventory
        property: MINIO_ROOT_PASSWORD
