{{- if .Values.inventoryApp.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inventory-app-external-secret
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: inventory-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.inventoryApp.externalSecret.secretPath }}
        property: DB_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-external-secret
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.inventoryApp.externalSecret.secretPath }}
        property: MYSQL_ROOT_PASSWORD
{{- end }}
